# Generated by Django 5.2.7 on 2025-10-31 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abr', models.CharField(max_length=100)),
                ('nom', models.TextField(blank=True)),
            ],
        ),
    ]
