# Generated by Django 5.2.8 on 2025-11-12 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction',
            name='abr',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='direction',
            name='nom',
            field=models.CharField(max_length=255),
        ),
    ]
