# Generated by Django 5.2.7 on 2025-11-16 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voiture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('direction', models.CharField(blank=True, max_length=100)),
                ('detenteur', models.CharField(blank=True, max_length=100)),
                ('couleur', models.CharField(blank=True, max_length=50)),
                ('etat', models.CharField(choices=[('en marche', 'En marche'), ('en panne', 'En panne'), ('en réparation', 'En réparation')], default='en marche', max_length=20)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
