# Generated by Django 5.2.7 on 2025-10-27 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voitures', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voiture',
            name='prix',
        ),
    ]
