# Generated by Django 5.2.7 on 2025-11-18 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voitures', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voiture',
            name='couleur',
        ),
        migrations.RemoveField(
            model_name='voiture',
            name='description',
        ),
        migrations.AddField(
            model_name='voiture',
            name='carte_grise',
            field=models.CharField(choices=[('Carte Grise', 'Carte Grise'), ('SCG', 'SCG'), ('Carte rose', 'Carte rose'), ('Carte rose(CG en cours)', 'Carte rose(CG en cours)'), ('attestation', 'Attestation'), ('lieux', 'Lieux')], default='Carte Grise', max_length=50),
        ),
        migrations.AddField(
            model_name='voiture',
            name='chauffeur',
            field=models.CharField(default='MNDPT', max_length=100),
        ),
        migrations.AddField(
            model_name='voiture',
            name='livret',
            field=models.CharField(choices=[('fait', 'Fait'), ('non fait', 'Non fait'), ('SLM', 'SLM')], default='non fait', max_length=20),
        ),
        migrations.AddField(
            model_name='voiture',
            name='marque',
            field=models.CharField(default='MNDPT', max_length=100),
        ),
        migrations.AddField(
            model_name='voiture',
            name='observation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='voiture',
            name='origine',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='detenteur',
            field=models.CharField(default='MNDPT', max_length=100),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='direction',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='etat',
            field=models.CharField(choices=[('bon etat', 'Bon état'), ('moyen', 'Moyen'), ('en panne', 'En panne')], default='bon etat', max_length=20),
        ),
    ]
