# Generated by Django 5.2.8 on 2025-11-19 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detenteurs', '0002_remove_detenteur_matricule_detenteur_direction_and_more'),
        ('voitures', '0002_remove_voiture_couleur_remove_voiture_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voiture',
            name='carte_grise',
            field=models.CharField(choices=[('Carte Grise', 'Carte Grise'), ('SCG', 'SCG'), ('Carte rose', 'Carte rose'), ('Carte rose(CG en cours)', 'Carte rose (CG en cours)'), ('attestation', 'Attestation'), ('lieux', 'Lieux')], default='Carte Grise', max_length=50),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='chauffeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voitures_conduites', to='detenteurs.detenteur'),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='detenteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voitures_detenu', to='detenteurs.detenteur'),
        ),
    ]
