# Generated by Django 5.2.8 on 2025-11-19 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detenteurs', '0001_initial'),
        ('directions', '0002_alter_direction_abr_alter_direction_nom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detenteur',
            name='matricule',
        ),
        migrations.AddField(
            model_name='detenteur',
            name='direction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='directions.direction'),
        ),
        migrations.AddField(
            model_name='detenteur',
            name='fonction',
            field=models.CharField(choices=[('detenteur', 'Détenteur'), ('chauffeur', 'Chauffeur'), ('les_deux', 'Les deux')], default='inconnu', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detenteur',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='detenteurs_photos/'),
        ),
        migrations.AddField(
            model_name='detenteur',
            name='prenom',
            field=models.CharField(default='inconnu', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detenteur',
            name='nom',
            field=models.CharField(max_length=100),
        ),
    ]
